name: Build Angular Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0' # Ou toute autre version compatible avec votre projet

    - name: Install Dependencies
      run: npm ci

    - name: Run Build
      run: npm run build
